version: 2.1
workflows:
  build_and_deploy:
    jobs:
      - build:
          context:
            - GITHUB
            - NPM
          filters:
            branches:
              only:
                - master
jobs:
  build:
    working_directory: ~/package
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Deploy Package
          command: |
            yarn
            yarn compile
            yarn release
